# Site settings
title: WnCC
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the official page for The Web and Coding Club of IIT Bombay.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "nihal111.github.io/" # the base hostname & protocol for your site
twitter_username: wncc_iitb
github_username:  wncc

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  soc_projects:
    output: true
  showcase_projects:
    output: true
  events:
    output: true

